development:
  adapter: postgresql
  encoding: unicode
  database: bird_watch-development
  pool: 5
  port: 5432
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: bird_watch-test
  pool: 5
  port: 5432
  host: localhost